## Packages

Packages are directory of python scripts.Some of the popular packages are Numpy, Matplotlib, pandas. In this exercise, We will be concerntrating more on the Numpy package.

## Imporating a package:

In [5]:
#Importing Numpy package into Python:
!pip install numpy    #Installing numpy using pip

  Using cached numpy-1.19.2-cp38-cp38-win_amd64.whl (13.0 MB)


In [7]:
import numpy as np    #Importing numpy into python

Creating an array using numpy:

Array are more like lists. They are declared like list. We can create n dimensional array in python.

In [9]:
a=[1,2,3,4]    #This is a list
array_a=np.array(a)    #Converting var 'a' of type list into an array using numpy.
print(a)
print(array_a)

[1, 2, 3, 4]
[1 2 3 4]


In [10]:
print(type(a))
print(type(array_a))

<class 'list'>
<class 'numpy.ndarray'>


Addition operation in an array:

In [11]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)    #Addition operation changes between a list and an array

[ 6  8 10 12]


2-D Array:

In [13]:
a=([1,2,3,4],
  [5,6,7,8],
  [9,10,11,12])

In [14]:
array_a=np.array(a)

Slicing:

In [20]:
print(array_a[0:1,0:2])    #The first inex in the square brackets corresponds to row, the last corresponds to column. 0:1 return row 1, 0:2 returns 1st,2nd column.

[[1 2]]


In [5]:
#Mean function
import numpy as np
a=[77,80,75,100,79]
a_np=np.array(a)
np.mean(a_np)    #Calculates mean value (avg)

82.2

In [6]:
print(np.median(a_np))    #Return the middle value

79.0


In [8]:
np.random.normal(1,1,10)    #To generate random values

array([ 1.43579619, -0.12685649, -0.37881128,  0.20946897,  0.11563112,
        0.91212533, -0.00152607,  1.03215874, -0.32912643,  1.35979847])