## Logic, control flow and filtering

Comparison Operators:

In [10]:
!pip install numpy
import numpy as np
a=[10,20,15,11,30,40,5,70]
np_a=np.array(a)
b=np_a > 20
print(b)
c=np_a[b]
print(c)


[False False False False  True  True False  True]
[30 40 70]


In [13]:
"Carl" < "Chris"    #String comparison, according alphabet Carl comes before Chris

True

In [14]:
x=3
y=2
x>=2

True

In [15]:
3 < "Chris"    #Python cannot compare data types such as str and int

TypeError: '<' not supported between instances of 'int' and 'str'

In [17]:
3 > 3.1    #Comparison between int and float is possible

False

Comparison Operators:

In [18]:
2 == (1+1)

True

In [19]:
True != False

True

In [20]:
"Python" != "python"

True

In [21]:
True == 1

True

In [22]:
True > False

True

In [23]:
H1=np.array([10,20,10,5,11])
H2=np.array([5,15,10,10,30])

In [24]:
H1 > 10

array([False,  True, False, False,  True])

In [25]:
H1 < H2

array([False, False, False,  True,  True])

Boolean operators:

In [26]:
# Operators and, or, not. For np array operation, logical_and(), logical_or(), logical_not() should be used for logical operations.
H1= 10
H2 = 20
print(H1 < 15 and H1 > 5)
print(H2 < 30 or H2 > 25)
print(H1 * 3 > H2 * 2)

True
True
False


In [27]:
H1=np.array([18,20,10.75,9.5])
H2=np.array([14,24,14.25,9])
print(np.logical_or(H1 > 18.5, H1 < 10))
print(np.logical_and(H1 < 11, H2 < 11))

[False  True False  True]
[False False False  True]


## if, elif, else

if

In [1]:
# Example:
z= 4
if z % 2 == 0:
    print("Even number")
else:
    print("Odd number")
    

Even number


elif

In [2]:
# Example 1:
z=3
if z % 2==0:
    print("Z is div by 2")
elif z % 3==0:
    print("Z is div by 3")
else:
    print("Z is neither div by 2 nor 3")

Z is div by 3


In [4]:
# Example 2:
z=6
if z % 2==0:
    print("Z is div by 2")    #True
elif z % 3==0:
    print("Z is div by 3")    #True, but this statement is never reached as the previous condition became true
else:
    print("Z is neither div by 2 nor 3")

Z is div by 2


In [10]:
# Example 3:
room = "bed"
area = 14.0
if room == "kit":
    print("kit")
elif room=="bed":
    print("bed")
else:
    print("False")
if area > 15.0:
    print("Big room")
elif area >= 14:
    print("Medium")
else:
    print("Pretty small")

bed
Medium


## Filtering Pandas dataframes

In [12]:
!pip install pandas    

In [18]:
import pandas as pd
brics=pd.read_csv("C:\Python Files\Source files/brics.csv",index_col=0)
print(brics)

         country    capital    area  population
BR        Brazil   Barsilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  Sout Afrrica   Pretoria   1.221       52.98


In [19]:
#1 Select area column
brics["area"]

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [23]:
# Alternative for above step
print(brics.loc[:,"area"])
print()
print(brics.iloc[:,2])

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64


In [25]:
#2 Comparison
is_huge=brics["area"] > 8

In [26]:
#3 Subset Dataframe
brics[is_huge]

country   capital    area  population
BR  Brazil  Barsilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

Boolean Operators:

In [27]:
import numpy as np
np.logical_and(brics["area"] > 8, brics["area"] < 10)

BR     True
RU    False
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [28]:
brics[np.logical_and(brics["area"] > 8, brics["area"] < 10)]

country   capital   area  population
BR  Brazil  Barsilia  8.516       200.4
CH   China   Beijing  9.597      1357.0